### ISSUE TITLE
Add "shares" settings for Proxmox hosts, helps with resource prioritisation

### ISSUE THREAD

**Issue by PC-Admin** [application-research/ehi-proxmaas#20]
RAM-Ballooning **and** "shares" need to be applied to more hosts for Proxmox to actually prioritize important VMs properly.

Mainly this is needed as the MooseFS masters are being OOM'd when RAM on Proxmox is running low. They should be prioritised to be the last VMs that are stopped if RAM is running low as they provide an essential service (storage) to everything else we are running!

Here's the particular module/setting we'd need to apply:
https://docs.ansible.com/ansible/latest/collections/community/general/proxmox_kvm_module.html#parameter-shares

**Comment by PC-Admin** [comment]
ChatGPT:

> The 'shares' settings in Proxmox is a relative system that influences the distribution of resources when there is contention. If you have a high priority VM and you've set its shares to a higher number (like 5000), it means that VM should get a larger share of the available resources compared to other VMs with lower shares. But, this doesn't guarantee that the VM won't be stopped if memory gets critically low.
> 
> Shares need to be set on all VMs/containers that you want to prioritize. The default share value is 1024, and any VMs/containers that do not have a specific share value set will use this default. The higher the share value of a VM, the higher priority it has when resources are distributed.
> 
> However, shares don't prevent a VM from being killed when the system is out of memory (OOM). Shares just affect the distribution of resources, not the absolute amount of memory that a VM can use.
> 
> If a high priority host is still getting killed due to OOM conditions despite having higher shares, then this might indicate that there's not enough memory on the host machine to handle the workloads of all the VMs it's running.
> 
> In this case, you might need to add more physical memory to the host machine, reduce the memory allocated to other VMs, or move some VMs to another host to reduce the overall memory usage.
> 
> You could also look at the swap usage and consider increasing the swap space, but this should be a last resort because swap space is much slower than physical memory.
> 
> **In addition, if you don't want a particular VM to be killed under any circumstances, you might want to look at the Linux kernel's OOM killer settings. Specifically, you can adjust the 'oom_score_adj' setting for the VM's process to make it less likely to be killed. However, be aware that this could potentially cause other processes to be killed instead.**

**Comment by PC-Admin** [comment]
Would there be any reasonable way to stop the kernel from OOM'ing these processes?

**Comment by Zorlin** [comment]
Yes, manually poking proc values is not that way. I'll think about it and
come up with something else. For now please don't do that... even if that
means evacuating nearly all machines off a Proxmox host to keep ram low
enough to avoid an OOM.
